name: auto_ai_find_job

#on:
  #schedule:
    #- cron: "0 16 * * *"  # 每天 UTC 时间 16:00（北京时间 00:00）运行
  #workflow_dispatch:  # 允许手动触发

jobs:
  login-task:
    runs-on: self-hosted  # 在本地运行

    steps:
      - name: 显示 Python 版本（确认使用本地 Python）
        run: python --version

      - name: 创建虚拟环境
        run: python -m venv venv

      - name: 激活虚拟环境并安装依赖
        run: |
          svenv\Scripts\activate && python main_find.py
          pip install -r requirements.txt
        shell: cmd  # 确保使用 bash 运行

      - name: 运行登录脚本
        run: |
          source venv/bin/activate  # Linux/macOS
          python login.py
        shell: bash

      - name: 关闭虚拟环境
        run: deactivate
        shell: bash
